sudo: false
services: 
  - docker

language: python

python: 
  - '3.6'

git:
  depth: false

addons:
  apt:
    packages:
      - docker-ce

env:
  global:
    - QGIS_IMAGE=qgis/qgis
    - QGIS_VERSION_TAG=final-3_4_4
    - PLUGIN_NAME=stdm
    - PG_IMAGE=gkahiu/docker-postgis-stdm
    - PG_VERSION_TAG=10
    - DOCKER_QGIS_TEST_DIR=tests_directory

matrix:
  include:
    - python: '3.6'

stages:
  - before_install
  - install
  - script
  - after_success
  - before_deploy
  - deploy
  - after_deploy

before_install:   
  # - docker version
  # - docker-compose version
  # - docker-compose up -d
  # - docker-compose ps
  # - sleep 10
  # - docker-compose exec qgis-testing-environment sh -c "qgis_setup.sh ${PLUGIN_NAME}"
  # - docker-compose exec qgis-testing-environment sh -c "pip3 install -r /${DOCKER_QGIS_TEST_DIR}/requirements.txt"

install: 
  # requirements
  - pip3 install -U pip;
  - pip3 install -r requirements.txt;

script:
# - docker-compose exec qgis-testing-environment sh -c "cd /${DOCKER_QGIS_TEST_DIR}"
# # - docker-compose exec qgis-testing-environment sh -c "black --check stdm" # failed - no stdm directory
# - docker-compose exec qgis-testing-environment sh -c "qgis_testrunner.sh stdm.tests.test_plugin"
# coverage test
- coverage run stdm/tests/test_plugin.py
# create coverage report
# - coverage report -m

after_success:
  - |
    if [[ $TRAVIS_BRANCH == "master" ]]; then
      coveralls;
      sphinx-build -Wv docs/source docs/build/html;
      sphinx-build -b html docs/source/ docs/build;
      echo "branch true";
    else
      [[ $TRAVIS_BRANCH != "master" && $TRAVIS_TAG == true]];
      coveralls;
      sphinx-build -Wv docs/source docs/build/html;
      sphinx-build -b html docs/source/ docs/build;
      echo "tag true";
    fi
  
before_deploy:
  - chmod +x -R scripts/

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $STDM_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep_history: true
    local_dir: docs # The folder that needs to be deployed
    repo: kngeno/stdm2 # Add your username/project_name here
    target_branch: gh-pages # Tell Travis to deploy on the gh-pages branch
    on:
      branch: master

  - provider: script
    script: bash scripts/deploy_skip.sh
    skip_cleanup: true
    on:
      branch: master

  - provider: script
    script: bash scripts/deploy_master.sh
    skip_cleanup: true
    on:
      branch: master
  
  - provider: script
    script: bash scripts/deploy_tags.sh
    skip_cleanup: true
    on:
      tags: true
      branch: master
      
  - provider: releases
    user: $USER
    password: $PASSWORD
    file:
      - stdm_*.tar.gz
      - stdm_*.zip
    
    file_glob: true
    skip_cleanup: true
    on:
      tags: true
      branch: master

after_deploy:
  - ls -lah stdm_*.tar.gz stdm_*.zip

notifications: 
  email: 
    on_failure: never #always
    on_success: never #always
    recipients: 
      - kngeno.kevin@gmail.com

